import = ['~/.config/alacritty/theme.toml']

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono NerdFont"

[shell]
program = "/usr/bin/zsh"

[window.dimensions]
columns = 110
lines = 35
