import = ["/home/takumi/.config/alacritty/noirbuddy-miaminight.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono"

[shell]
program = "/usr/bin/zsh"

[window.dimensions]
columns = 110
lines = 35
