
[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "JetBrains Mono NerdFont"

[terminal.shell]
program = "/usr/bin/zsh"

[window.dimensions]
columns = 110
lines = 35

[general]
import = ['~/.config/alacritty/kanagawa_wave.toml']

[terminal]
