# aura.toml with customization

[colors.primary]
background = "#18181a"
foreground = "#f5f5f5"

[colors.cursor]
cursor = "#f5f5f5"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#18181a"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#f5f5f5"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#18181a"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#f5f5f5"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"
